services:
  - type: web
    name: django-portfolio
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn my_portfolio.wsgi:application"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: portfolio_site.settings
      - key: PYTHON_VERSION
        value: "3.11"
