# Generated by Django 5.2.4 on 2025-07-28 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(help_text='Emoji or Icon', max_length=10)),
                ('category', models.CharField(help_text='Category e.g. Frontend', max_length=100)),
                ('stack', models.TextField(help_text='Tech stack or description')),
            ],
        ),
    ]
