# Generated by Django 5.2.4 on 2025-08-11 18:55

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_skill"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpost",
            name="content",
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name="project",
            name="description",
            field=ckeditor.fields.RichTextField(),
        ),
    ]
