# Generated by Django 5.2.4 on 2025-08-18 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_sociallink"),
    ]

    operations = [
        migrations.CreateModel(
            name="About",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(default="About Me 📂", max_length=255)),
                ("tagline", models.CharField(blank=True, max_length=255, null=True)),
                ("description_1", models.TextField(blank=True, null=True)),
                ("description_2", models.TextField(blank=True, null=True)),
                ("description_3", models.TextField(blank=True, null=True)),
                (
                    "tech_stack",
                    models.TextField(
                        blank=True,
                        help_text="Enter tech stack details in plain text or HTML (e.g., <b>Frontend:</b> React, Tailwind)",
                        null=True,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
