# Generated by Django 5.2.4 on 2025-08-18 13:01

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_about"),
    ]

    operations = [
        migrations.AlterField(
            model_name="about",
            name="description_1",
            field=ckeditor_uploader.fields.RichTextUploadingField(
                blank=True, null=True
            ),
        ),
        migrations.AlterField(
            model_name="about",
            name="description_2",
            field=ckeditor_uploader.fields.RichTextUploadingField(
                blank=True, null=True
            ),
        ),
        migrations.AlterField(
            model_name="about",
            name="description_3",
            field=ckeditor_uploader.fields.RichTextUploadingField(
                blank=True, null=True
            ),
        ),
        migrations.AlterField(
            model_name="about",
            name="tagline",
            field=ckeditor_uploader.fields.RichTextUploadingField(
                blank=True, max_length=255, null=True
            ),
        ),
        migrations.AlterField(
            model_name="about",
            name="title",
            field=models.CharField(default="📂 About Me ", max_length=255),
        ),
    ]
