# Generated by Django 5.2.4 on 2025-08-18 13:03

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_alter_about_description_1_alter_about_description_2_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="about",
            name="tech_stack",
            field=ckeditor_uploader.fields.RichTextUploadingField(
                blank=True,
                help_text="Enter tech stack details in plain text or HTML (e.g., <b>Frontend:</b> React, Tailwind)",
                null=True,
            ),
        ),
    ]
