# Generated by Django 5.2.4 on 2025-08-18 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_alter_about_tech_stack"),
    ]

    operations = [
        migrations.CreateModel(
            name="Hero",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("greeting", models.CharField(default="Hi 👋, I'm", max_length=255)),
                ("name", models.CharField(default="Ronny Karani", max_length=255)),
                (
                    "emoji",
                    models.CharField(
                        blank=True, default="👨\u200d💻", max_length=10, null=True
                    ),
                ),
                (
                    "headline",
                    models.CharField(
                        default="A Full-Stack Software Engineer | Building Scalable, Impact-Driven Digital Solutions",
                        max_length=255,
                    ),
                ),
                ("subtext_1", models.TextField(blank=True, null=True)),
                ("subtext_2", models.TextField(blank=True, null=True)),
                ("subtext_3", models.TextField(blank=True, null=True)),
                (
                    "resume",
                    models.FileField(blank=True, null=True, upload_to="resumes/"),
                ),
                (
                    "profile_image",
                    models.ImageField(
                        blank=True, default="ron.jpeg", null=True, upload_to="hero/"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name="blogpost",
            name="excerpt",
            field=models.TextField(blank=True, null=True),
        ),
    ]
