# Generated by Django 5.2.4 on 2025-08-18 13:40

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_hero_alter_blogpost_excerpt"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hero",
            name="headline",
            field=models.CharField(
                default="A Full-Stack Software Engineer, Building Scalable &  Impact-Driven Digital Solutions",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="hero",
            name="subtext_1",
            field=ckeditor_uploader.fields.RichTextUploadingField(
                blank=True, null=True
            ),
        ),
        migrations.AlterField(
            model_name="hero",
            name="subtext_2",
            field=ckeditor_uploader.fields.RichTextUploadingField(
                blank=True, null=True
            ),
        ),
        migrations.AlterField(
            model_name="hero",
            name="subtext_3",
            field=ckeditor_uploader.fields.RichTextUploadingField(
                blank=True, null=True
            ),
        ),
    ]
