# Generated by Django 5.2.4 on 2025-08-18 13:48

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_alter_hero_headline_alter_hero_subtext_1_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hero",
            name="headline",
            field=ckeditor_uploader.fields.RichTextUploadingField(
                blank=True,
                default="A Full-Stack Software Engineer, Building Scalable &  Impact-Driven Digital Solutions",
                max_length=255,
                null=True,
            ),
        ),
    ]
