# Generated by Django 5.2.4 on 2025-08-18 14:30

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_alter_hero_headline"),
    ]

    operations = [
        migrations.AlterField(
            model_name="skill",
            name="stack",
            field=ckeditor_uploader.fields.RichTextUploadingField(
                help_text="Tech stack or description"
            ),
        ),
    ]
