# Generated by Django 5.2.4 on 2025-08-18 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_alter_skill_stack"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="created_at",
            field=models.DateField(auto_now_add=True),
        ),
    ]
