# Generated by Django 5.2.4 on 2025-08-18 15:41

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_testimonial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="testimonial",
            name="message",
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
