# Generated by Django 5.0.7 on 2025-08-22 13:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_testimonial_rating"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="skill",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddField(
            model_name="skill",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
